// Generated by gencpp from file collision_avoidance/CalcStopDuration.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H
#define COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H

#include <ros/service_traits.h>


#include <collision_avoidance/CalcStopDurationRequest.h>
#include <collision_avoidance/CalcStopDurationResponse.h>


namespace collision_avoidance
{

struct CalcStopDuration
{

typedef CalcStopDurationRequest Request;
typedef CalcStopDurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcStopDuration
} // namespace collision_avoidance


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collision_avoidance::CalcStopDuration > {
  static const char* value()
  {
    return "a8531c49262635abe6abcd3257d5d874";
  }

  static const char* value(const ::collision_avoidance::CalcStopDuration&) { return value(); }
};

template<>
struct DataType< ::collision_avoidance::CalcStopDuration > {
  static const char* value()
  {
    return "collision_avoidance/CalcStopDuration";
  }

  static const char* value(const ::collision_avoidance::CalcStopDuration&) { return value(); }
};


// service_traits::MD5Sum< ::collision_avoidance::CalcStopDurationRequest> should match
// service_traits::MD5Sum< ::collision_avoidance::CalcStopDuration >
template<>
struct MD5Sum< ::collision_avoidance::CalcStopDurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::collision_avoidance::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance::CalcStopDurationRequest> should match
// service_traits::DataType< ::collision_avoidance::CalcStopDuration >
template<>
struct DataType< ::collision_avoidance::CalcStopDurationRequest>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::collision_avoidance::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collision_avoidance::CalcStopDurationResponse> should match
// service_traits::MD5Sum< ::collision_avoidance::CalcStopDuration >
template<>
struct MD5Sum< ::collision_avoidance::CalcStopDurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::collision_avoidance::CalcStopDurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance::CalcStopDurationResponse> should match
// service_traits::DataType< ::collision_avoidance::CalcStopDuration >
template<>
struct DataType< ::collision_avoidance::CalcStopDurationResponse>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::collision_avoidance::CalcStopDurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H
