// Generated by gencpp from file Collision_Avoidance/CalcStopDuration.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H
#define COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H

#include <ros/service_traits.h>


#include <Collision_Avoidance/CalcStopDurationRequest.h>
#include <Collision_Avoidance/CalcStopDurationResponse.h>


namespace Collision_Avoidance
{

struct CalcStopDuration
{

typedef CalcStopDurationRequest Request;
typedef CalcStopDurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcStopDuration
} // namespace Collision_Avoidance


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Collision_Avoidance::CalcStopDuration > {
  static const char* value()
  {
    return "a8531c49262635abe6abcd3257d5d874";
  }

  static const char* value(const ::Collision_Avoidance::CalcStopDuration&) { return value(); }
};

template<>
struct DataType< ::Collision_Avoidance::CalcStopDuration > {
  static const char* value()
  {
    return "Collision_Avoidance/CalcStopDuration";
  }

  static const char* value(const ::Collision_Avoidance::CalcStopDuration&) { return value(); }
};


// service_traits::MD5Sum< ::Collision_Avoidance::CalcStopDurationRequest> should match
// service_traits::MD5Sum< ::Collision_Avoidance::CalcStopDuration >
template<>
struct MD5Sum< ::Collision_Avoidance::CalcStopDurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Collision_Avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::Collision_Avoidance::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Collision_Avoidance::CalcStopDurationRequest> should match
// service_traits::DataType< ::Collision_Avoidance::CalcStopDuration >
template<>
struct DataType< ::Collision_Avoidance::CalcStopDurationRequest>
{
  static const char* value()
  {
    return DataType< ::Collision_Avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::Collision_Avoidance::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Collision_Avoidance::CalcStopDurationResponse> should match
// service_traits::MD5Sum< ::Collision_Avoidance::CalcStopDuration >
template<>
struct MD5Sum< ::Collision_Avoidance::CalcStopDurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Collision_Avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::Collision_Avoidance::CalcStopDurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Collision_Avoidance::CalcStopDurationResponse> should match
// service_traits::DataType< ::Collision_Avoidance::CalcStopDuration >
template<>
struct DataType< ::Collision_Avoidance::CalcStopDurationResponse>
{
  static const char* value()
  {
    return DataType< ::Collision_Avoidance::CalcStopDuration >::value();
  }
  static const char* value(const ::Collision_Avoidance::CalcStopDurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_CALCSTOPDURATION_H
