// Generated by gencpp from file Collision_Avoidance/FlagStop.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H
#define COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H

#include <ros/service_traits.h>


#include <Collision_Avoidance/FlagStopRequest.h>
#include <Collision_Avoidance/FlagStopResponse.h>


namespace Collision_Avoidance
{

struct FlagStop
{

typedef FlagStopRequest Request;
typedef FlagStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FlagStop
} // namespace Collision_Avoidance


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Collision_Avoidance::FlagStop > {
  static const char* value()
  {
    return "7b0aefe35bb755536b8814d5dcb2c19d";
  }

  static const char* value(const ::Collision_Avoidance::FlagStop&) { return value(); }
};

template<>
struct DataType< ::Collision_Avoidance::FlagStop > {
  static const char* value()
  {
    return "Collision_Avoidance/FlagStop";
  }

  static const char* value(const ::Collision_Avoidance::FlagStop&) { return value(); }
};


// service_traits::MD5Sum< ::Collision_Avoidance::FlagStopRequest> should match
// service_traits::MD5Sum< ::Collision_Avoidance::FlagStop >
template<>
struct MD5Sum< ::Collision_Avoidance::FlagStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Collision_Avoidance::FlagStop >::value();
  }
  static const char* value(const ::Collision_Avoidance::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Collision_Avoidance::FlagStopRequest> should match
// service_traits::DataType< ::Collision_Avoidance::FlagStop >
template<>
struct DataType< ::Collision_Avoidance::FlagStopRequest>
{
  static const char* value()
  {
    return DataType< ::Collision_Avoidance::FlagStop >::value();
  }
  static const char* value(const ::Collision_Avoidance::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Collision_Avoidance::FlagStopResponse> should match
// service_traits::MD5Sum< ::Collision_Avoidance::FlagStop >
template<>
struct MD5Sum< ::Collision_Avoidance::FlagStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Collision_Avoidance::FlagStop >::value();
  }
  static const char* value(const ::Collision_Avoidance::FlagStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Collision_Avoidance::FlagStopResponse> should match
// service_traits::DataType< ::Collision_Avoidance::FlagStop >
template<>
struct DataType< ::Collision_Avoidance::FlagStopResponse>
{
  static const char* value()
  {
    return DataType< ::Collision_Avoidance::FlagStop >::value();
  }
  static const char* value(const ::Collision_Avoidance::FlagStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H
