// Generated by gencpp from file collision_avoidance/FlagStopResponse.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPRESPONSE_H
#define COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collision_avoidance
{
template <class ContainerAllocator>
struct FlagStopResponse_
{
  typedef FlagStopResponse_<ContainerAllocator> Type;

  FlagStopResponse_()
    : flag_stop(false)  {
    }
  FlagStopResponse_(const ContainerAllocator& _alloc)
    : flag_stop(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_stop_type;
  _flag_stop_type flag_stop;





  typedef boost::shared_ptr< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FlagStopResponse_

typedef ::collision_avoidance::FlagStopResponse_<std::allocator<void> > FlagStopResponse;

typedef boost::shared_ptr< ::collision_avoidance::FlagStopResponse > FlagStopResponsePtr;
typedef boost::shared_ptr< ::collision_avoidance::FlagStopResponse const> FlagStopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_avoidance::FlagStopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collision_avoidance::FlagStopResponse_<ContainerAllocator1> & lhs, const ::collision_avoidance::FlagStopResponse_<ContainerAllocator2> & rhs)
{
  return lhs.flag_stop == rhs.flag_stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collision_avoidance::FlagStopResponse_<ContainerAllocator1> & lhs, const ::collision_avoidance::FlagStopResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collision_avoidance

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05b5eaa636771131c617bd4935b80111";
  }

  static const char* value(const ::collision_avoidance::FlagStopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05b5eaa636771131ULL;
  static const uint64_t static_value2 = 0xc617bd4935b80111ULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_avoidance/FlagStopResponse";
  }

  static const char* value(const ::collision_avoidance::FlagStopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag_stop\n"
"\n"
;
  }

  static const char* value(const ::collision_avoidance::FlagStopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlagStopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_avoidance::FlagStopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collision_avoidance::FlagStopResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "flag_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPRESPONSE_H
