// Generated by gencpp from file collision_avoidance/FlagStop.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H
#define COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H

#include <ros/service_traits.h>


#include <collision_avoidance/FlagStopRequest.h>
#include <collision_avoidance/FlagStopResponse.h>


namespace collision_avoidance
{

struct FlagStop
{

typedef FlagStopRequest Request;
typedef FlagStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FlagStop
} // namespace collision_avoidance


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collision_avoidance::FlagStop > {
  static const char* value()
  {
    return "7b0aefe35bb755536b8814d5dcb2c19d";
  }

  static const char* value(const ::collision_avoidance::FlagStop&) { return value(); }
};

template<>
struct DataType< ::collision_avoidance::FlagStop > {
  static const char* value()
  {
    return "collision_avoidance/FlagStop";
  }

  static const char* value(const ::collision_avoidance::FlagStop&) { return value(); }
};


// service_traits::MD5Sum< ::collision_avoidance::FlagStopRequest> should match
// service_traits::MD5Sum< ::collision_avoidance::FlagStop >
template<>
struct MD5Sum< ::collision_avoidance::FlagStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance::FlagStop >::value();
  }
  static const char* value(const ::collision_avoidance::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance::FlagStopRequest> should match
// service_traits::DataType< ::collision_avoidance::FlagStop >
template<>
struct DataType< ::collision_avoidance::FlagStopRequest>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance::FlagStop >::value();
  }
  static const char* value(const ::collision_avoidance::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collision_avoidance::FlagStopResponse> should match
// service_traits::MD5Sum< ::collision_avoidance::FlagStop >
template<>
struct MD5Sum< ::collision_avoidance::FlagStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance::FlagStop >::value();
  }
  static const char* value(const ::collision_avoidance::FlagStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance::FlagStopResponse> should match
// service_traits::DataType< ::collision_avoidance::FlagStop >
template<>
struct DataType< ::collision_avoidance::FlagStopResponse>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance::FlagStop >::value();
  }
  static const char* value(const ::collision_avoidance::FlagStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_FLAGSTOP_H
