// Generated by gencpp from file collision_avoidance/FlagStopRequest.msg
// DO NOT EDIT!


#ifndef COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPREQUEST_H
#define COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collision_avoidance
{
template <class ContainerAllocator>
struct FlagStopRequest_
{
  typedef FlagStopRequest_<ContainerAllocator> Type;

  FlagStopRequest_()
    : T_stop(0.0)
    , q()
    , q_p()
    , q_pp()  {
    }
  FlagStopRequest_(const ContainerAllocator& _alloc)
    : T_stop(0.0)
    , q(_alloc)
    , q_p(_alloc)
    , q_pp(_alloc)  {
  (void)_alloc;
    }



   typedef double _T_stop_type;
  _T_stop_type T_stop;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_type;
  _q_type q;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_p_type;
  _q_p_type q_p;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_pp_type;
  _q_pp_type q_pp;





  typedef boost::shared_ptr< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FlagStopRequest_

typedef ::collision_avoidance::FlagStopRequest_<std::allocator<void> > FlagStopRequest;

typedef boost::shared_ptr< ::collision_avoidance::FlagStopRequest > FlagStopRequestPtr;
typedef boost::shared_ptr< ::collision_avoidance::FlagStopRequest const> FlagStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_avoidance::FlagStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collision_avoidance::FlagStopRequest_<ContainerAllocator1> & lhs, const ::collision_avoidance::FlagStopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.T_stop == rhs.T_stop &&
    lhs.q == rhs.q &&
    lhs.q_p == rhs.q_p &&
    lhs.q_pp == rhs.q_pp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collision_avoidance::FlagStopRequest_<ContainerAllocator1> & lhs, const ::collision_avoidance::FlagStopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collision_avoidance

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e024533f10287e7f7806c4581eb65396";
  }

  static const char* value(const ::collision_avoidance::FlagStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe024533f10287e7fULL;
  static const uint64_t static_value2 = 0x7806c4581eb65396ULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_avoidance/FlagStopRequest";
  }

  static const char* value(const ::collision_avoidance::FlagStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 T_stop\n"
"float64[] q\n"
"float64[] q_p\n"
"float64[] q_pp\n"
;
  }

  static const char* value(const ::collision_avoidance::FlagStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.T_stop);
      stream.next(m.q);
      stream.next(m.q_p);
      stream.next(m.q_pp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlagStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_avoidance::FlagStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collision_avoidance::FlagStopRequest_<ContainerAllocator>& v)
  {
    s << indent << "T_stop: ";
    Printer<double>::stream(s, indent + "  ", v.T_stop);
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "q_p[]" << std::endl;
    for (size_t i = 0; i < v.q_p.size(); ++i)
    {
      s << indent << "  q_p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_p[i]);
    }
    s << indent << "q_pp[]" << std::endl;
    for (size_t i = 0; i < v.q_pp.size(); ++i)
    {
      s << indent << "  q_pp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_pp[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_AVOIDANCE_MESSAGE_FLAGSTOPREQUEST_H
