(cl:defpackage def_proj-srv
  (:use )
  (:export
   "CALCSTOPDURATION"
   "<CALCSTOPDURATION-REQUEST>"
   "CALCSTOPDURATION-REQUEST"
   "<CALCSTOPDURATION-RESPONSE>"
   "CALCSTOPDURATION-RESPONSE"
   "CALCVALIDTRAJ"
   "<CALCVALIDTRAJ-REQUEST>"
   "CALCVALIDTRAJ-REQUEST"
   "<CALCVALIDTRAJ-RESPONSE>"
   "CALCVALIDTRAJ-RESPONSE"
   "FLAGSTOP"
   "<FLAGSTOP-REQUEST>"
   "FLAGSTOP-REQUEST"
   "<FLAGSTOP-RESPONSE>"
   "FLAGSTOP-RESPONSE"
  ))

