// Generated by gencpp from file def_proj/CalcValidTraj.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_MESSAGE_CALCVALIDTRAJ_H
#define DEF_PROJ_MESSAGE_CALCVALIDTRAJ_H

#include <ros/service_traits.h>


#include <def_proj/CalcValidTrajRequest.h>
#include <def_proj/CalcValidTrajResponse.h>


namespace def_proj
{

struct CalcValidTraj
{

typedef CalcValidTrajRequest Request;
typedef CalcValidTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcValidTraj
} // namespace def_proj


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::def_proj::CalcValidTraj > {
  static const char* value()
  {
    return "70855c1f975352ceba80c99de40d0931";
  }

  static const char* value(const ::def_proj::CalcValidTraj&) { return value(); }
};

template<>
struct DataType< ::def_proj::CalcValidTraj > {
  static const char* value()
  {
    return "def_proj/CalcValidTraj";
  }

  static const char* value(const ::def_proj::CalcValidTraj&) { return value(); }
};


// service_traits::MD5Sum< ::def_proj::CalcValidTrajRequest> should match
// service_traits::MD5Sum< ::def_proj::CalcValidTraj >
template<>
struct MD5Sum< ::def_proj::CalcValidTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj::CalcValidTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj::CalcValidTrajRequest> should match
// service_traits::DataType< ::def_proj::CalcValidTraj >
template<>
struct DataType< ::def_proj::CalcValidTrajRequest>
{
  static const char* value()
  {
    return DataType< ::def_proj::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj::CalcValidTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::def_proj::CalcValidTrajResponse> should match
// service_traits::MD5Sum< ::def_proj::CalcValidTraj >
template<>
struct MD5Sum< ::def_proj::CalcValidTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj::CalcValidTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj::CalcValidTrajResponse> should match
// service_traits::DataType< ::def_proj::CalcValidTraj >
template<>
struct DataType< ::def_proj::CalcValidTrajResponse>
{
  static const char* value()
  {
    return DataType< ::def_proj::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj::CalcValidTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEF_PROJ_MESSAGE_CALCVALIDTRAJ_H
