// Generated by gencpp from file def_proj/FlagStop.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_MESSAGE_FLAGSTOP_H
#define DEF_PROJ_MESSAGE_FLAGSTOP_H

#include <ros/service_traits.h>


#include <def_proj/FlagStopRequest.h>
#include <def_proj/FlagStopResponse.h>


namespace def_proj
{

struct FlagStop
{

typedef FlagStopRequest Request;
typedef FlagStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FlagStop
} // namespace def_proj


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::def_proj::FlagStop > {
  static const char* value()
  {
    return "7b0aefe35bb755536b8814d5dcb2c19d";
  }

  static const char* value(const ::def_proj::FlagStop&) { return value(); }
};

template<>
struct DataType< ::def_proj::FlagStop > {
  static const char* value()
  {
    return "def_proj/FlagStop";
  }

  static const char* value(const ::def_proj::FlagStop&) { return value(); }
};


// service_traits::MD5Sum< ::def_proj::FlagStopRequest> should match
// service_traits::MD5Sum< ::def_proj::FlagStop >
template<>
struct MD5Sum< ::def_proj::FlagStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj::FlagStop >::value();
  }
  static const char* value(const ::def_proj::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj::FlagStopRequest> should match
// service_traits::DataType< ::def_proj::FlagStop >
template<>
struct DataType< ::def_proj::FlagStopRequest>
{
  static const char* value()
  {
    return DataType< ::def_proj::FlagStop >::value();
  }
  static const char* value(const ::def_proj::FlagStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::def_proj::FlagStopResponse> should match
// service_traits::MD5Sum< ::def_proj::FlagStop >
template<>
struct MD5Sum< ::def_proj::FlagStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj::FlagStop >::value();
  }
  static const char* value(const ::def_proj::FlagStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj::FlagStopResponse> should match
// service_traits::DataType< ::def_proj::FlagStop >
template<>
struct DataType< ::def_proj::FlagStopResponse>
{
  static const char* value()
  {
    return DataType< ::def_proj::FlagStop >::value();
  }
  static const char* value(const ::def_proj::FlagStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEF_PROJ_MESSAGE_FLAGSTOP_H
