// Generated by gencpp from file def_proj_Panda/CalcValidTrajResponse.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJRESPONSE_H
#define DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace def_proj_Panda
{
template <class ContainerAllocator>
struct CalcValidTrajResponse_
{
  typedef CalcValidTrajResponse_<ContainerAllocator> Type;

  CalcValidTrajResponse_()
    : flag_valid(0)  {
    }
  CalcValidTrajResponse_(const ContainerAllocator& _alloc)
    : flag_valid(0)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_valid_type;
  _flag_valid_type flag_valid;





  typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalcValidTrajResponse_

typedef ::def_proj_Panda::CalcValidTrajResponse_<std::allocator<void> > CalcValidTrajResponse;

typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajResponse > CalcValidTrajResponsePtr;
typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajResponse const> CalcValidTrajResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator2> & rhs)
{
  return lhs.flag_valid == rhs.flag_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace def_proj_Panda

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f8b8de568edd8c7dce07a786ddd4501";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f8b8de568edd8c7ULL;
  static const uint64_t static_value2 = 0xdce07a786ddd4501ULL;
};

template<class ContainerAllocator>
struct DataType< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def_proj_Panda/CalcValidTrajResponse";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 flag_valid\n"
"\n"
;
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalcValidTrajResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::def_proj_Panda::CalcValidTrajResponse_<ContainerAllocator>& v)
  {
    s << indent << "flag_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJRESPONSE_H
