// Generated by gencpp from file def_proj_Panda/CalcStopDurationResponse.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONRESPONSE_H
#define DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace def_proj_Panda
{
template <class ContainerAllocator>
struct CalcStopDurationResponse_
{
  typedef CalcStopDurationResponse_<ContainerAllocator> Type;

  CalcStopDurationResponse_()
    : stop_duration(0.0)  {
    }
  CalcStopDurationResponse_(const ContainerAllocator& _alloc)
    : stop_duration(0.0)  {
  (void)_alloc;
    }



   typedef double _stop_duration_type;
  _stop_duration_type stop_duration;





  typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalcStopDurationResponse_

typedef ::def_proj_Panda::CalcStopDurationResponse_<std::allocator<void> > CalcStopDurationResponse;

typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationResponse > CalcStopDurationResponsePtr;
typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationResponse const> CalcStopDurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.stop_duration == rhs.stop_duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace def_proj_Panda

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "596df0feed32a80b1c46d99baf544050";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x596df0feed32a80bULL;
  static const uint64_t static_value2 = 0x1c46d99baf544050ULL;
};

template<class ContainerAllocator>
struct DataType< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def_proj_Panda/CalcStopDurationResponse";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 stop_duration\n"
"\n"
;
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalcStopDurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::def_proj_Panda::CalcStopDurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "stop_duration: ";
    Printer<double>::stream(s, indent + "  ", v.stop_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONRESPONSE_H
