// Generated by gencpp from file def_proj_Panda/CalcValidTraj.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJ_H
#define DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJ_H

#include <ros/service_traits.h>


#include <def_proj_Panda/CalcValidTrajRequest.h>
#include <def_proj_Panda/CalcValidTrajResponse.h>


namespace def_proj_Panda
{

struct CalcValidTraj
{

typedef CalcValidTrajRequest Request;
typedef CalcValidTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcValidTraj
} // namespace def_proj_Panda


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::def_proj_Panda::CalcValidTraj > {
  static const char* value()
  {
    return "70855c1f975352ceba80c99de40d0931";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTraj&) { return value(); }
};

template<>
struct DataType< ::def_proj_Panda::CalcValidTraj > {
  static const char* value()
  {
    return "def_proj_Panda/CalcValidTraj";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTraj&) { return value(); }
};


// service_traits::MD5Sum< ::def_proj_Panda::CalcValidTrajRequest> should match
// service_traits::MD5Sum< ::def_proj_Panda::CalcValidTraj >
template<>
struct MD5Sum< ::def_proj_Panda::CalcValidTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj_Panda::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcValidTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj_Panda::CalcValidTrajRequest> should match
// service_traits::DataType< ::def_proj_Panda::CalcValidTraj >
template<>
struct DataType< ::def_proj_Panda::CalcValidTrajRequest>
{
  static const char* value()
  {
    return DataType< ::def_proj_Panda::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcValidTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::def_proj_Panda::CalcValidTrajResponse> should match
// service_traits::MD5Sum< ::def_proj_Panda::CalcValidTraj >
template<>
struct MD5Sum< ::def_proj_Panda::CalcValidTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj_Panda::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcValidTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj_Panda::CalcValidTrajResponse> should match
// service_traits::DataType< ::def_proj_Panda::CalcValidTraj >
template<>
struct DataType< ::def_proj_Panda::CalcValidTrajResponse>
{
  static const char* value()
  {
    return DataType< ::def_proj_Panda::CalcValidTraj >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcValidTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJ_H
