// Generated by gencpp from file def_proj_Panda/CalcStopDuration.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATION_H
#define DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATION_H

#include <ros/service_traits.h>


#include <def_proj_Panda/CalcStopDurationRequest.h>
#include <def_proj_Panda/CalcStopDurationResponse.h>


namespace def_proj_Panda
{

struct CalcStopDuration
{

typedef CalcStopDurationRequest Request;
typedef CalcStopDurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcStopDuration
} // namespace def_proj_Panda


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::def_proj_Panda::CalcStopDuration > {
  static const char* value()
  {
    return "a8531c49262635abe6abcd3257d5d874";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDuration&) { return value(); }
};

template<>
struct DataType< ::def_proj_Panda::CalcStopDuration > {
  static const char* value()
  {
    return "def_proj_Panda/CalcStopDuration";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDuration&) { return value(); }
};


// service_traits::MD5Sum< ::def_proj_Panda::CalcStopDurationRequest> should match
// service_traits::MD5Sum< ::def_proj_Panda::CalcStopDuration >
template<>
struct MD5Sum< ::def_proj_Panda::CalcStopDurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj_Panda::CalcStopDuration >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj_Panda::CalcStopDurationRequest> should match
// service_traits::DataType< ::def_proj_Panda::CalcStopDuration >
template<>
struct DataType< ::def_proj_Panda::CalcStopDurationRequest>
{
  static const char* value()
  {
    return DataType< ::def_proj_Panda::CalcStopDuration >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcStopDurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::def_proj_Panda::CalcStopDurationResponse> should match
// service_traits::MD5Sum< ::def_proj_Panda::CalcStopDuration >
template<>
struct MD5Sum< ::def_proj_Panda::CalcStopDurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::def_proj_Panda::CalcStopDuration >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcStopDurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::def_proj_Panda::CalcStopDurationResponse> should match
// service_traits::DataType< ::def_proj_Panda::CalcStopDuration >
template<>
struct DataType< ::def_proj_Panda::CalcStopDurationResponse>
{
  static const char* value()
  {
    return DataType< ::def_proj_Panda::CalcStopDuration >::value();
  }
  static const char* value(const ::def_proj_Panda::CalcStopDurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATION_H
