// Generated by gencpp from file def_proj_Panda/CalcValidTrajRequest.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJREQUEST_H
#define DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace def_proj_Panda
{
template <class ContainerAllocator>
struct CalcValidTrajRequest_
{
  typedef CalcValidTrajRequest_<ContainerAllocator> Type;

  CalcValidTrajRequest_()
    : q_s()
    , q_e()
    , traj_duration(0.0)
    , traj_step(0.0)  {
    }
  CalcValidTrajRequest_(const ContainerAllocator& _alloc)
    : q_s(_alloc)
    , q_e(_alloc)
    , traj_duration(0.0)
    , traj_step(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_s_type;
  _q_s_type q_s;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_e_type;
  _q_e_type q_e;

   typedef double _traj_duration_type;
  _traj_duration_type traj_duration;

   typedef double _traj_step_type;
  _traj_step_type traj_step;





  typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalcValidTrajRequest_

typedef ::def_proj_Panda::CalcValidTrajRequest_<std::allocator<void> > CalcValidTrajRequest;

typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajRequest > CalcValidTrajRequestPtr;
typedef boost::shared_ptr< ::def_proj_Panda::CalcValidTrajRequest const> CalcValidTrajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q_s == rhs.q_s &&
    lhs.q_e == rhs.q_e &&
    lhs.traj_duration == rhs.traj_duration &&
    lhs.traj_step == rhs.traj_step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace def_proj_Panda

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "847840f1b2b2579ff9a09bad22f082db";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x847840f1b2b2579fULL;
  static const uint64_t static_value2 = 0xf9a09bad22f082dbULL;
};

template<class ContainerAllocator>
struct DataType< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def_proj_Panda/CalcValidTrajRequest";
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q_s\n"
"float64[] q_e\n"
"float64 traj_duration\n"
"float64 traj_step\n"
;
  }

  static const char* value(const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q_s);
      stream.next(m.q_e);
      stream.next(m.traj_duration);
      stream.next(m.traj_step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalcValidTrajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::def_proj_Panda::CalcValidTrajRequest_<ContainerAllocator>& v)
  {
    s << indent << "q_s[]" << std::endl;
    for (size_t i = 0; i < v.q_s.size(); ++i)
    {
      s << indent << "  q_s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_s[i]);
    }
    s << indent << "q_e[]" << std::endl;
    for (size_t i = 0; i < v.q_e.size(); ++i)
    {
      s << indent << "  q_e[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_e[i]);
    }
    s << indent << "traj_duration: ";
    Printer<double>::stream(s, indent + "  ", v.traj_duration);
    s << indent << "traj_step: ";
    Printer<double>::stream(s, indent + "  ", v.traj_step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCVALIDTRAJREQUEST_H
