// Generated by gencpp from file def_proj_Panda/CalcStopDurationRequest.msg
// DO NOT EDIT!


#ifndef DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONREQUEST_H
#define DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace def_proj_Panda
{
template <class ContainerAllocator>
struct CalcStopDurationRequest_
{
  typedef CalcStopDurationRequest_<ContainerAllocator> Type;

  CalcStopDurationRequest_()
    : q()
    , q_p()
    , q_pp()  {
    }
  CalcStopDurationRequest_(const ContainerAllocator& _alloc)
    : q(_alloc)
    , q_p(_alloc)
    , q_pp(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_type;
  _q_type q;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_p_type;
  _q_p_type q_p;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_pp_type;
  _q_pp_type q_pp;





  typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalcStopDurationRequest_

typedef ::def_proj_Panda::CalcStopDurationRequest_<std::allocator<void> > CalcStopDurationRequest;

typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationRequest > CalcStopDurationRequestPtr;
typedef boost::shared_ptr< ::def_proj_Panda::CalcStopDurationRequest const> CalcStopDurationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q &&
    lhs.q_p == rhs.q_p &&
    lhs.q_pp == rhs.q_pp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator1> & lhs, const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace def_proj_Panda

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fd5787f799b6515a9da80500d9f73fc";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fd5787f799b6515ULL;
  static const uint64_t static_value2 = 0xa9da80500d9f73fcULL;
};

template<class ContainerAllocator>
struct DataType< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def_proj_Panda/CalcStopDurationRequest";
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q\n"
"float64[] q_p\n"
"float64[] q_pp\n"
;
  }

  static const char* value(const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
      stream.next(m.q_p);
      stream.next(m.q_pp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalcStopDurationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::def_proj_Panda::CalcStopDurationRequest_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "q_p[]" << std::endl;
    for (size_t i = 0; i < v.q_p.size(); ++i)
    {
      s << indent << "  q_p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_p[i]);
    }
    s << indent << "q_pp[]" << std::endl;
    for (size_t i = 0; i < v.q_pp.size(); ++i)
    {
      s << indent << "  q_pp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_pp[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEF_PROJ_PANDA_MESSAGE_CALCSTOPDURATIONREQUEST_H
