(cl:defpackage Collision_Avoidance-srv
  (:use )
  (:export
   "CALCSTOPDURATION"
   "<CALCSTOPDURATION-REQUEST>"
   "CALCSTOPDURATION-REQUEST"
   "<CALCSTOPDURATION-RESPONSE>"
   "CALCSTOPDURATION-RESPONSE"
   "FLAGSTOP"
   "<FLAGSTOP-REQUEST>"
   "FLAGSTOP-REQUEST"
   "<FLAGSTOP-RESPONSE>"
   "FLAGSTOP-RESPONSE"
  ))

